services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-EXEC", "pg_isready -U pasteuser -d pastebin"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "4174:4174"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge